feat: cmd for images
- gpustack list-images to list available images, include runtime and runner.
- gpustack save-images to save available images to local path as Docker Archive.
- gpustack copy-images to copy available images to destination registry.

Signed-off-by: thxCode <thxcode0824@gmail.com>

diff --git a/pack/Dockerfile b/pack/Dockerfile
--- a/pack/Dockerfile
+++ b/pack/Dockerfile
@@ -391,7 +391,53 @@ COPY pack/higress-configs/ /
 ENV GPUSTACK_HIGRESS_PLUGIN_DIR=/opt/data/plugins
 ## END Install Higress standalone components
 
-## Install
+## Install Skopeo
+
+RUN <<EOF
+    # Skopeo
+
+    # Install Skopeo for images mirroring
+    apt-get update -y && apt-get install -y --no-install-recommends \
+        skopeo
+
+    IFS="." read -r MAJOR MINOR PATCH <<< "$(skopeo --version | awk '{print $3}' | cut -d'-' -f1)"
+    if (( MAJOR < 1 || ( MAJOR == 1 && MINOR < 14 ) )); then
+        echo "Skopeo version ${MAJOR}.${MINOR} is lower than required 1.13.3, upgrading from source..."
+
+        apt-get install -y --no-install-recommends \
+            libgpgme-dev \
+            libdevmapper-dev
+
+        # Install Go
+        curl --retry 3 --retry-connrefused -fL "https://go.dev/dl/go1.18.10.${TARGETOS}-${TARGETARCH}.tar.gz" | tar -zx -C /usr/local
+        export PATH="/usr/local/go/bin:${PATH}"
+
+        # Install Skopeo from source
+        git -C /tmp clone --recursive --shallow-submodules \
+            --depth 1 --branch v1.13.3 --single-branch \
+            https://github.com/containers/skopeo.git skopeo
+
+        # Build and install
+        pushd /tmp/skopeo \
+            && make vendor \
+            && DISABLE_DOCS=1 PREFIX=/usr make install-binary
+
+        # Review
+        skopeo --version
+
+        # Cleanup
+        go clean -cache -modcache -testcache \
+            && rm -rf /usr/local/go \
+            && rm -rf /root/.cache/go-build
+    fi
+
+    # Cleanup
+    rm -rf /var/tmp/* \
+        && rm -rf /tmp/* \
+        && rm -rf /var/cache/apt
+EOF
+
+## Install GPUStack
 
 RUN --mount=type=cache,target=/root/.cache \
     --mount=type=bind,target=/workspace/gpustack,rw \
